[package]
name = "montyformat"
version = "0.9.0"
edition = "2021"
authors = ["Jamie Whiting"]
description = "Compressed data formats for Monty"
license = "MIT"
readme = "README.md"

[profile.release]
panic = 'abort'
strip = true
lto = true
codegen-units = 1
